---
- name: install go-agent
  become: yes
  apt:
    name: go-agent
    state: latest

- name: Recursively change ownership of a directory
  ansible.builtin.file:
   path: /usr/share/go-agent/
   state: directory
   recurse: yes
   owner: "{{ GOCD_USER }}"
   group: "{{ GOCD_GROUP }}"

- name: Replace go-agent template
  ansible.builtin.template:
    src: wrapper-properties.conf.j2
    dest: /usr/share/go-agent/wrapper-config/wrapper-properties.conf
    mode: '0771'
  notify:
    - Restart go-agent
