---
#Install PostgreSQL DB in go-server
- name: add postagresql-gpg-key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: create variable
  command: sudo sh -c "echo \"deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main\" "
  register: repo_link
  
- debug: 
    msg: "{{ repo_link.stdout }}"
  
- name: Add postagresql repo
  apt_repository:
    repo: "{{ repo_link.stdout }}"
    state: present
    filename: pgdg

- name: update all service
  become: yes
  apt:
    update_cache: yes
  
# - name: Install Database in go-server (It might take some to install all dependencies)
#   apt: name={{ item }} state=present
#   with_items:
#     - postgresql
#     - postgresql-contrib
#     - postgresql-client
#     - python3-psycopg2
#     - acl
#     - python3-pip

- name: Replace the word peer to trust in pg_hba.conf file.
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    search_string: 'postgres'
    line: local   all             postgres                                trust
  notify:
    - Restart postgres

# create DB, Role, Alter Role and Grant All Privileages

- name: Create a new database with name "gocd"
  community.postgresql.postgresql_db:
    name: "{{ GOCD_DATABASE | default('gocd_database') }}"
    encoding: "UTF-8" 
    template: "template0"
    owner: "postgres"
  become: yes
  become_user: postgres
  register: DB
  
- debug:
    var: DB
  
- name: create go user
  community.postgresql.postgresql_user:
    name: "{{ GOCD_DATABASE_USER | default('gocd_database_user') }}"
    password: "{{ GOCD_DATABASE_PASSWORD | default('gocd_database_password') }}"
    role_attr_flags: SUPERUSER
    encrypted: yes
    state: present
  become: yes
  become_user: postgres
  
- name: Change database owner postgres to "gocd_user"
  community.postgresql.postgresql_db:
    name: "{{ GOCD_DATABASE | default('gocd_database') }}"
    owner: "{{ GOCD_DATABASE_USER | default('gocd_database_user') }}"
  become: yes
  become_user: postgres

- name: GRANT ALL PRIVILEGES ON database "gocd" to "user"
  community.postgresql.postgresql_privs:
    db: "{{ GOCD_DATABASE | default('gocd_database') }}"
    privs: ALL
    type: database
    objs: "{{ GOCD_DATABASE | default('gocd_database') }}"
    role: "{{ GOCD_DATABASE_USER | default('gocd_database_user') }}"
    grant_option: yes
  become: yes
  become_user: postgres

- name: Copy db.properties with owner and permissions
  ansible.builtin.copy:
    src: db.properties
    dest: /etc/go/
    owner: "{{ GOCD_USER }}"
    group: "{{ GOCD_GROUP }}"
    mode: '0664'
   
- name: start go-server service 
  become: yes
  service:
    name: go-server
    state: started
    enabled: yes

- name: sleep for 20 seconds 
  wait_for:
    timeout: 30

- name: Alter Role of user
  community.postgresql.postgresql_user:
    name: "{{ GOCD_DATABASE_USER | default('gocd_database_user') }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE,INHERIT,LOGIN
  become: yes
  become_user: postgres    

- name: Replace the word peer to trust in pg_hba.conf file.
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    line: local   {{ GOCD_DATABASE | default('gocd_database') }}  {{ GOCD_DATABASE_USER | default('gocd_database_user') }}              trust
  notify:
    - Restart postgres
# ...