---
#Instaling to go-server
- name: install go-server
  become: yes
  apt:
    name: go-server
    state: latest

- name: Recursively change ownership of a directory
  ansible.builtin.file:
    path: /usr/share/go-server/
    state: directory
    recurse: yes
    owner: "{{ GOCD_USER | default('go') }}"
    group: "{{ GOCD_GROUP | default('gocd') }}"
...